apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}          # Release name, e.g., order-release-blue
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: LoadBalancer                  # This tells Kubernetes to provision a cloud LB
  selector:
    app: {{ .Release.Name }}          # Must match Deployment labels
  ports:
    - name: http
      port: {{ .Values.service.port | default 8080 }}      # External LB port
      targetPort: {{ .Values.service.port | default 8080 }} # Container port
