apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc   # Adds "-svc" to match the pipeline
spec:
  type: {{ .Values.service.type | default "LoadBalancer" }}
  selector:
    app: {{ .Release.Name }}      # Matches pod labels created by Helm release
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: {{ .Values.service.port | default 8080 }}
